// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VinhKhanhGuide.Infrastructure.Persistence;

#nullable disable

namespace VinhKhanhGuide.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403144130_InitialCreateStalls")]
    partial class InitialCreateStalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VinhKhanhGuide.Domain.Entities.Stall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OpenHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("TriggerRadiusMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Stalls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.50m,
                            Category = "Hai san",
                            DescriptionVi = "Quan oc mau sample noi bat voi cac mon oc xao bo toi va oc huong nuong phuc vu khach du lich.",
                            ImageUrl = "https://example.com/sample-stalls/oc-co-lan.jpg",
                            Latitude = 10.76042,
                            Longitude = 106.69320999999999,
                            Name = "Oc Co Lan",
                            OpenHours = "16:00-23:00",
                            TriggerRadiusMeters = 40.0
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4.20m,
                            Category = "Do nuong",
                            DescriptionVi = "Diem nuong sample tren duong Vinh Khanh voi thit nuong, hai san nuong va khong gian ngoai troi don gian.",
                            ImageUrl = "https://example.com/sample-stalls/nuong-gio-dem.jpg",
                            Latitude = 10.76088,
                            Longitude = 106.69401999999999,
                            Name = "Nuong Gio Dem",
                            OpenHours = "17:00-23:30",
                            TriggerRadiusMeters = 45.0
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.70m,
                            Category = "Hai san",
                            DescriptionVi = "Quan sample chuyen cua rang me, tom xoc toi va cac mon hai san dam vi phu hop de demo danh sach gian hang.",
                            ImageUrl = "https://example.com/sample-stalls/cua-rang-me.jpg",
                            Latitude = 10.759969999999999,
                            Longitude = 106.69374999999999,
                            Name = "So 1 Cua Rang Me",
                            OpenHours = "15:30-22:30",
                            TriggerRadiusMeters = 35.0
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 4.10m,
                            Category = "Lau",
                            DescriptionVi = "Quan lau sample gia dinh voi cac mon lau hai san, lau thai va lau bo duoc tao de seed du lieu khoi dau.",
                            ImageUrl = "https://example.com/sample-stalls/lau-dem-vinh-khanh.jpg",
                            Latitude = 10.760109999999999,
                            Longitude = 106.69450999999999,
                            Name = "Lau Dem Vinh Khanh",
                            OpenHours = "16:30-23:00",
                            TriggerRadiusMeters = 50.0
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 4.00m,
                            Category = "An vat",
                            DescriptionVi = "Xe banh trang nuong sample nho gon, phuc vu mon an vat buoi toi voi trung, pho mai va kho bo.",
                            ImageUrl = "https://example.com/sample-stalls/banh-trang-nuong-198.jpg",
                            Latitude = 10.76102,
                            Longitude = 106.69347999999999,
                            Name = "Banh Trang Nuong 198",
                            OpenHours = "18:00-22:00",
                            TriggerRadiusMeters = 30.0
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 4.30m,
                            Category = "Mon nuoc",
                            DescriptionVi = "Quan sample phuc vu chao muc nong, muc chien va mon an nhe phu hop khach tham quan cuoi buoi.",
                            ImageUrl = "https://example.com/sample-stalls/chao-muc-co-ba.jpg",
                            Latitude = 10.760529999999999,
                            Longitude = 106.69488,
                            Name = "Chao Muc Co Ba",
                            OpenHours = "17:30-22:30",
                            TriggerRadiusMeters = 35.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
