// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VinhKhanhGuide.Infrastructure.Persistence;

#nullable disable

namespace VinhKhanhGuide.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409114208_AddPoiReadyFieldsToStalls")]
    partial class AddPoiReadyFieldsToStalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VinhKhanhGuide.Domain.Entities.Stall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MapLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NarrationScriptVi")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OpenHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double>("TriggerRadiusMeters")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Stalls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "https://example.com/sample-audio/oc-co-lan.mp3",
                            AverageRating = 4.50m,
                            Category = "Hai san",
                            DescriptionVi = "Quan oc mau sample noi bat voi cac mon oc xao bo toi va oc huong nuong phuc vu khach du lich.",
                            ImageUrl = "https://example.com/sample-stalls/oc-co-lan.jpg",
                            IsActive = true,
                            Latitude = 10.76042,
                            Longitude = 106.69320999999999,
                            MapLink = "https://maps.apple.com/?ll=10.76042,106.69321&q=Oc%20Co%20Lan",
                            Name = "Oc Co Lan",
                            NarrationScriptVi = "Ban dang den gan Oc Co Lan, mot diem dung chan sample noi bat voi cac mon oc xao bo toi va oc huong nuong tren duong Vinh Khanh.",
                            OpenHours = "16:00-23:00",
                            Priority = 100,
                            TriggerRadiusMeters = 40.0
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "https://example.com/sample-audio/nuong-gio-dem.mp3",
                            AverageRating = 4.20m,
                            Category = "Do nuong",
                            DescriptionVi = "Diem nuong sample tren duong Vinh Khanh voi thit nuong, hai san nuong va khong gian ngoai troi don gian.",
                            ImageUrl = "https://example.com/sample-stalls/nuong-gio-dem.jpg",
                            IsActive = true,
                            Latitude = 10.76088,
                            Longitude = 106.69401999999999,
                            MapLink = "https://maps.apple.com/?ll=10.76088,106.69402&q=Nuong%20Gio%20Dem",
                            Name = "Nuong Gio Dem",
                            NarrationScriptVi = "Nuong Gio Dem la diem POI sample phu hop cho narration ve khong gian an toi ngoai troi va cac mon nuong pho bien cua khu vuc.",
                            OpenHours = "17:00-23:30",
                            Priority = 90,
                            TriggerRadiusMeters = 45.0
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "https://example.com/sample-audio/cua-rang-me.mp3",
                            AverageRating = 4.70m,
                            Category = "Hai san",
                            DescriptionVi = "Quan sample chuyen cua rang me, tom xoc toi va cac mon hai san dam vi phu hop de demo danh sach gian hang.",
                            ImageUrl = "https://example.com/sample-stalls/cua-rang-me.jpg",
                            IsActive = true,
                            Latitude = 10.759969999999999,
                            Longitude = 106.69374999999999,
                            MapLink = "https://maps.apple.com/?ll=10.75997,106.69375&q=So%201%20Cua%20Rang%20Me",
                            Name = "So 1 Cua Rang Me",
                            NarrationScriptVi = "So 1 Cua Rang Me duoc seed nhu mot diem ke chuyen sample cho cac mon hai san dam vi va nhiep song buoi toi tren tuyen pho am thuc.",
                            OpenHours = "15:30-22:30",
                            Priority = 80,
                            TriggerRadiusMeters = 35.0
                        },
                        new
                        {
                            Id = 4,
                            AudioUrl = "https://example.com/sample-audio/lau-dem-vinh-khanh.mp3",
                            AverageRating = 4.10m,
                            Category = "Lau",
                            DescriptionVi = "Quan lau sample gia dinh voi cac mon lau hai san, lau thai va lau bo duoc tao de seed du lieu khoi dau.",
                            ImageUrl = "https://example.com/sample-stalls/lau-dem-vinh-khanh.jpg",
                            IsActive = true,
                            Latitude = 10.760109999999999,
                            Longitude = 106.69450999999999,
                            MapLink = "https://maps.apple.com/?ll=10.76011,106.69451&q=Lau%20Dem%20Vinh%20Khanh",
                            Name = "Lau Dem Vinh Khanh",
                            NarrationScriptVi = "Lau Dem Vinh Khanh la diem narration sample cho nhom du khach muon dung chan lau hon va tim mon lau hai san vao buoi toi.",
                            OpenHours = "16:30-23:00",
                            Priority = 70,
                            TriggerRadiusMeters = 50.0
                        },
                        new
                        {
                            Id = 5,
                            AudioUrl = "https://example.com/sample-audio/banh-trang-nuong-198.mp3",
                            AverageRating = 4.00m,
                            Category = "An vat",
                            DescriptionVi = "Xe banh trang nuong sample nho gon, phuc vu mon an vat buoi toi voi trung, pho mai va kho bo.",
                            ImageUrl = "https://example.com/sample-stalls/banh-trang-nuong-198.jpg",
                            IsActive = true,
                            Latitude = 10.76102,
                            Longitude = 106.69347999999999,
                            MapLink = "https://maps.apple.com/?ll=10.76102,106.69348&q=Banh%20Trang%20Nuong%20198",
                            Name = "Banh Trang Nuong 198",
                            NarrationScriptVi = "Banh Trang Nuong 198 dai dien cho nhom diem POI an vat sample, huu ich khi app muon kich hoat narration ngan o cu ly gan.",
                            OpenHours = "18:00-22:00",
                            Priority = 60,
                            TriggerRadiusMeters = 30.0
                        },
                        new
                        {
                            Id = 6,
                            AudioUrl = "https://example.com/sample-audio/chao-muc-co-ba.mp3",
                            AverageRating = 4.30m,
                            Category = "Mon nuoc",
                            DescriptionVi = "Quan sample phuc vu chao muc nong, muc chien va mon an nhe phu hop khach tham quan cuoi buoi.",
                            ImageUrl = "https://example.com/sample-stalls/chao-muc-co-ba.jpg",
                            IsActive = true,
                            Latitude = 10.760529999999999,
                            Longitude = 106.69488,
                            MapLink = "https://maps.apple.com/?ll=10.76053,106.69488&q=Chao%20Muc%20Co%20Ba",
                            Name = "Chao Muc Co Ba",
                            NarrationScriptVi = "Chao Muc Co Ba duoc giu lam POI sample cho nhung diem dung cuoi hanh trinh, noi du khach co the nghe tom tat va tim mon an nhe.",
                            OpenHours = "17:30-22:30",
                            Priority = 50,
                            TriggerRadiusMeters = 35.0
                        });
                });

            modelBuilder.Entity("VinhKhanhGuide.Domain.Entities.StallTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("LastGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StallId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StallId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("StallTranslations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
